use four_weeks;
CREATE TABLE user (id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(50), 
    username VARCHAR(50) UNIQUE, avatar_url VARCHAR(200));

CREATE TABLE submission(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, 
    description VARCHAR(500) NOT NULL, picture VARCHAR(200), demo VARCHAR(200), 
    code VARCHAR(200) NOT NULL, user_id INT NOT NULL, 
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE);